apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: vt-server-node
  name: vt-server-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: vt-server-node
    spec:
      containers:
      - image: gcr.io/souzoh-demo-gcp-001/sinmetal/vstore_tester:latest
        name: vt-server-node