application: vstore-tester
module: default
version: 1
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /cron/.*
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
